version: "3"
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Assuming your Nuxt.js app runs on port 3000
    volumes:
      - ./path/to/your/nuxt-app:/app
    depends_on:
      - postgres
    command: sh -c "npm install && npm run db:migrate && npm run db:seed && npm run dev"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/nuxt_db"
    links:
      - postgres

  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nuxt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
